export const skillsSeed = [
  { name: 'React', slug: 'react', category: 'framework' },
  { name: 'TypeScript', slug: 'typescript', category: 'language' },
  { name: 'JavaScript', slug: 'javascript', category: 'language' },
  { name: 'Node.js', slug: 'nodejs', category: 'runtime' },
  { name: 'Python', slug: 'python', category: 'language' },
  { name: 'NestJS', slug: 'nestjs', category: 'framework' },
  { name: 'Next.js', slug: 'nextjs', category: 'framework' },
  { name: 'Vue.js', slug: 'vuejs', category: 'framework' },
  { name: 'Angular', slug: 'angular', category: 'framework' },
  { name: 'Tailwind CSS', slug: 'tailwind-css', category: 'framework' },
  { name: 'PostgreSQL', slug: 'postgresql', category: 'database' },
  { name: 'MongoDB', slug: 'mongodb', category: 'database' },
  { name: 'Redis', slug: 'redis', category: 'database' },
  { name: 'Docker', slug: 'docker', category: 'tool' },
  { name: 'AWS', slug: 'aws', category: 'cloud' },
  { name: 'Git', slug: 'git', category: 'tool' },
  { name: 'Figma', slug: 'figma', category: 'design' },
  { name: 'GraphQL', slug: 'graphql', category: 'tool' },
  { name: 'REST API', slug: 'rest-api', category: 'tool' },
  { name: 'Ethereum', slug: 'ethereum', category: 'blockchain' },
  { name: 'Solidity', slug: 'solidity', category: 'language' },
  { name: 'IPFS', slug: 'ipfs', category: 'blockchain' },
  { name: 'Express.js', slug: 'expressjs', category: 'framework' },
  { name: 'Java', slug: 'java', category: 'language' },
  { name: 'C#', slug: 'csharp', category: 'language' },
  { name: 'Go', slug: 'go', category: 'language' },
  { name: 'Rust', slug: 'rust', category: 'language' },
  { name: 'Swift', slug: 'swift', category: 'language' },
  { name: 'Kotlin', slug: 'kotlin', category: 'language' },
  { name: 'Flutter', slug: 'flutter', category: 'framework' },
  { name: 'React Native', slug: 'react-native', category: 'framework' },
  { name: 'Sass', slug: 'sass', category: 'tool' },
  { name: 'Webpack', slug: 'webpack', category: 'tool' },
  { name: 'Vite', slug: 'vite', category: 'tool' },
  { name: 'Jest', slug: 'jest', category: 'tool' },
  { name: 'MySQL', slug: 'mysql', category: 'database' },
  { name: 'Firebase', slug: 'firebase', category: 'cloud' },
  { name: 'Vercel', slug: 'vercel', category: 'cloud' },
  { name: 'Linux', slug: 'linux', category: 'tool' },
  { name: 'CI/CD', slug: 'ci-cd', category: 'tool' },
];
